# Generated by Django 5.0.4 on 2025-01-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_cash',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
