# Generated by Django 5.1.4 on 2025-01-27 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacion',
            name='idbodega',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.bodega'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reparacion',
            name='idempleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.empleado'),
            preserve_default=False,
        ),
    ]
