# Generated by Django 5.1.4 on 2025-01-27 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_reparacion_idbodega_reparacion_idempleado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reparacion',
            old_name='idbodega',
            new_name='bodega_origen',
        ),
    ]
