# Generated by Django 5.0.4 on 2025-01-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_precio_cash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dui', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=200)),
                ('nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='factura',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='detallefactura',
            name='id_factura',
        ),
        migrations.RemoveField(
            model_name='detallefactura',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='iva',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='cedula',
            new_name='dui',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='correo2',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='nacimiento',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='telefono2',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='DetalleFactura',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
