# Generated by Django 5.1.4 on 2025-01-27 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_rename_idbodega_reparacion_bodega_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoproducto',
            name='nombre',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Dañado', 'Dañado'), ('En reparación', 'En reparación'), ('Reparado', 'Reparado'), ('Vendido', 'Vendido'), ('Pendiente', 'Pendiente')], default='Disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.estadoproducto'),
        ),
    ]
