# Generated by Django 5.1.4 on 2025-01-27 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_estadoproducto_nombre_alter_reparacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devolucion',
            name='dañado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='idbodega',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.bodega'),
            preserve_default=False,
        ),
    ]
