# Generated by Django 5.1.4 on 2025-01-31 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_estado_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Pendiente', max_length=100)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.bodega')),
                ('empleado_entrego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleado_entrego', to=settings.AUTH_USER_MODEL)),
                ('empleado_recibio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleado_recibio', to='inventario.empleado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
    ]
