# Generated by Django 5.0.4 on 2025-01-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_rename_precio_producto_precio_unitario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodega',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='bodega',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='idbodega',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='id_pedido',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='id_producto',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='idproducto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='notificaciones',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Opciones',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='Bodega',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
        migrations.DeleteModel(
            name='EstadoProducto',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Notificaciones',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='PedidoItem',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
