# Generated by Django 5.1.4 on 2025-01-27 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_devolucion_cantidad_devolucion_dañado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='idempleado_recibio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.empleado'),
            preserve_default=False,
        ),
    ]
