# Generated by Django 5.1.4 on 2025-01-27 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_devolucion_idempleado_recibio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='idempleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.empleado'),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='idempleado_recibio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
