# Generated by Django 5.0.4 on 2025-01-15 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_categoria_empleado_estado_estadoproducto_marca_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
