# Generated by Django 5.1.4 on 2025-01-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_devolucion_idempleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacion',
            name='desde_devolucion',
            field=models.BooleanField(default=False),
        ),
    ]
