# Generated by Django 5.1.4 on 2025-02-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_empleado_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='codigo',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
