# Generated by Django 5.1.4 on 2025-01-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_reparacion_desde_devolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='enviado_a_reparacion',
            field=models.BooleanField(default=False),
        ),
    ]
