# Generated by Django 5.0.4 on 2025-01-15 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_delete_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opciones',
            name='valor_iva',
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True)),
                ('idempleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('id_empleado_autorizo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizo_entregas', to=settings.AUTH_USER_MODEL)),
                ('id_empleado_recibio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibio_entregas', to=settings.AUTH_USER_MODEL)),
                ('idbodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.bodega')),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('sub_monto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monto_general', models.DecimalField(decimal_places=2, max_digits=20)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.empleado', to_field='dui')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.factura')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('reparacion', 'Reparacion'), ('devolucion', 'Devolucion'), ('entrega', 'Entrega'), ('pendiente', 'Pendiente')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.bodega')),
                ('estado_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.estadoproducto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('tipo_recepcion', models.CharField(choices=[('vendido', 'Vendido'), ('devuelto', 'Devuelto')], max_length=8)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('id_empleado_autorizo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizo_recepciones', to=settings.AUTH_USER_MODEL)),
                ('id_empleado_devolvio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devolvio_recepciones', to=settings.AUTH_USER_MODEL)),
                ('idbodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.bodega')),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_problema', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_retorno', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('reparado', 'Reparado')], default='pendiente', max_length=9)),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
    ]
