# Generated by Django 5.1.4 on 2025-01-27 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_devolucion_enviado_a_reparacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reparacion',
            old_name='descripcion_problema',
            new_name='motivo',
        ),
    ]
