# Generated by Django 5.1.4 on 2025-02-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_empleado_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='correo',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
