# Generated by Django 5.0.4 on 2025-01-15 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_remove_opciones_valor_iva_devolucion_entrega_factura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='presente',
        ),
    ]
