# Generated by Django 5.1.4 on 2025-02-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_empleado_correo_alter_empleado_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoproducto',
            name='tipo_movimiento',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('reparacion', 'Reparacion'), ('devolucion', 'Devolucion'), ('entrega', 'Entrega'), ('recepcion', 'Recepción'), ('venta', 'Venta'), ('pendiente', 'Pendiente'), ('transferencia', 'Transferencia')], max_length=20),
        ),
    ]
