# Generated by Django 5.0.4 on 2025-01-16 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_remove_pedido_presente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetallePedido',
            new_name='DetalleCompra',
        ),
        migrations.RenameField(
            model_name='detallecompra',
            old_name='id_pedido',
            new_name='id_compra',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='direccion',
        ),
        migrations.RenameModel(
            old_name='Pedido',
            new_name='Compra',
        ),
        migrations.CreateModel(
            name='CompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.bodega')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='PedidoItem',
        ),
    ]
