# Generated by Django 5.0.4 on 2025-01-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_rename_detallepedido_detallecompra_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='marca',
            new_name='nombre',
        ),
    ]
