# Generated by Django 5.1.4 on 2025-01-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_rename_marca_marca_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado',
            old_name='estado',
            new_name='nombre',
        ),
    ]
