# Generated by Django 5.1.4 on 2025-01-18 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_rename_estado_estado_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
