# Generated by Django 5.1.4 on 2025-01-20 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_remove_producto_disponible_remove_producto_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompra',
            name='id_compra',
        ),
        migrations.RemoveField(
            model_name='compraitem',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='compraitem',
            name='bodega',
        ),
        migrations.RemoveField(
            model_name='compraitem',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='recepcion',
            name='id_empleado_devolvio',
        ),
        migrations.AddField(
            model_name='movimientoproducto',
            name='empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.empleado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepcion',
            name='id_empleado_recibio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recibio_recepciones', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='correo',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='id_empleado_recibio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibio_entregas', to='inventario.empleado'),
        ),
        migrations.AlterField(
            model_name='estadoproducto',
            name='nombre',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Dañado', 'Dañado'), ('En reparación', 'En reparación'), ('Vendido', 'Vendido'), ('Pendiente', 'Pendiente')], default='Disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='tipo_recepcion',
            field=models.CharField(choices=[('vendido', 'Vendido'), ('devuelto', 'Devuelto')], max_length=9),
        ),
        migrations.CreateModel(
            name='RegistroInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.bodega')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.estadoproducto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='CompraItem',
        ),
        migrations.DeleteModel(
            name='DetalleCompra',
        ),
    ]
