# Generated by Django 5.1.4 on 2025-01-20 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_remove_detallecompra_id_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.estadoproducto'),
            preserve_default=False,
        ),
    ]
