# Generated by Django 5.0.4 on 2025-01-15 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_estadoproducto_devolucion_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoproducto',
            name='tipo_movimiento',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('reparacion', 'Reparacion'), ('devolucion', 'Devolucion'), ('entrega', 'Entrega'), ('pendiente', 'Pendiente')], max_length=10),
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.bodega')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='control.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.producto')),
            ],
        ),
    ]
